name: Update README

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          DATE="$(date)"
          sed -i "s|Last update: .*|Last update: $DATE|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "Tassadit"
          git config --global user.email "tassaditaksas03@gmail.com"
          git add README.md
          git commit -m "Auto update README" || echo "No changes"
          git push
